# Generated by Django 5.2.7 on 2026-03-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredSubreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('web_development', 'Web Development'), ('seo', 'SEO'), ('shopify', 'Shopify'), ('digital_marketing', 'Digital Marketing'), ('design', 'Design'), ('app_development', 'App Development'), ('automation_ai', 'Automation / AI')], max_length=50)),
                ('subreddit', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['service_category', 'subreddit'],
                'unique_together': {('service_category', 'subreddit')},
            },
        ),
        migrations.CreateModel(
            name='RedditLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_post_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('ups', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('service_category', models.CharField(choices=[('web_development', 'Web Development'), ('seo', 'SEO'), ('shopify', 'Shopify'), ('digital_marketing', 'Digital Marketing'), ('design', 'Design'), ('app_development', 'App Development'), ('automation_ai', 'Automation / AI')], max_length=50)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_category'], name='leads_reddi_service_937e9c_idx'), models.Index(fields=['scraped_at'], name='leads_reddi_scraped_a196bf_idx')],
            },
        ),
    ]
