# Generated by Django 5.2.7 on 2026-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartRedditLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_post_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('ups', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('service_category', models.CharField(choices=[('web_development', 'Web Development'), ('seo', 'SEO'), ('shopify', 'Shopify'), ('digital_marketing', 'Digital Marketing'), ('design', 'Design'), ('app_development', 'App Development'), ('automation_ai', 'Automation / AI')], max_length=50)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_category'], name='leads_smart_service_a4ffc1_idx'), models.Index(fields=['scraped_at'], name='leads_smart_scraped_7b358f_idx')],
            },
        ),
    ]
