# Generated by Django 5.2.7 on 2026-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_smartredditlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartredditlead',
            name='classification',
            field=models.CharField(choices=[('lead', 'Lead'), ('maybe_lead', 'Maybe Lead'), ('noise', 'Noise')], default='lead', max_length=20),
        ),
        migrations.AddField(
            model_name='smartredditlead',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smartredditlead',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smartredditlead',
            name='reason_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='smartredditlead',
            index=models.Index(fields=['classification'], name='leads_smart_classif_5704de_idx'),
        ),
    ]
