# Generated by Django 5.2.7 on 2026-04-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_smartredditlead_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditLeadTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('subreddit', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('intent_score', models.FloatField(default=0.0)),
                ('model_confidence', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('matched_signals', models.JSONField(default=list)),
                ('user_label', models.BooleanField()),
                ('labeled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-labeled_at'],
            },
        ),
    ]
