# Generated by Django 5.2.7 on 2026-04-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_redditleadtrainingdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedditLead',
        ),
    ]
